// Copyright (c) 2022 NTT Communications Corporation
//
// This software is released under the MIT License.
// see https://github.com/nttcom/pola/blob/main/LICENSE

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/pola/v1/pola.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PCEService_CreateSRPolicy_FullMethodName     = "/api.pola.v1.PCEService/CreateSRPolicy"
	PCEService_DeleteSRPolicy_FullMethodName     = "/api.pola.v1.PCEService/DeleteSRPolicy"
	PCEService_GetSessionList_FullMethodName     = "/api.pola.v1.PCEService/GetSessionList"
	PCEService_GetSRPolicyList_FullMethodName    = "/api.pola.v1.PCEService/GetSRPolicyList"
	PCEService_GetTED_FullMethodName             = "/api.pola.v1.PCEService/GetTED"
	PCEService_DeleteSession_FullMethodName      = "/api.pola.v1.PCEService/DeleteSession"
	PCEService_AddExcludedNode_FullMethodName    = "/api.pola.v1.PCEService/AddExcludedNode"
	PCEService_RemoveExcludedNode_FullMethodName = "/api.pola.v1.PCEService/RemoveExcludedNode"
	PCEService_GetExcludedNodes_FullMethodName   = "/api.pola.v1.PCEService/GetExcludedNodes"
)

// PCEServiceClient is the client API for PCEService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PCEServiceClient interface {
	CreateSRPolicy(ctx context.Context, in *CreateSRPolicyRequest, opts ...grpc.CallOption) (*CreateSRPolicyResponse, error)
	DeleteSRPolicy(ctx context.Context, in *DeleteSRPolicyRequest, opts ...grpc.CallOption) (*DeleteSRPolicyResponse, error)
	GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*GetSessionListResponse, error)
	GetSRPolicyList(ctx context.Context, in *GetSRPolicyListRequest, opts ...grpc.CallOption) (*GetSRPolicyListResponse, error)
	GetTED(ctx context.Context, in *GetTEDRequest, opts ...grpc.CallOption) (*GetTEDResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// AddExcludedNode/RemoveExcludedNode/GetExcludedNodes manage the global
	// node-exclusion set: router IDs kept out of CSPF consideration for every
	// dynamically-computed policy server-wide, independent of any single
	// policy's own SRPolicy.exclude. See the SRPolicy.exclude_router_ids /
	// exclude_sids comments for the equivalent per-policy mechanism.
	AddExcludedNode(ctx context.Context, in *AddExcludedNodeRequest, opts ...grpc.CallOption) (*AddExcludedNodeResponse, error)
	RemoveExcludedNode(ctx context.Context, in *RemoveExcludedNodeRequest, opts ...grpc.CallOption) (*RemoveExcludedNodeResponse, error)
	GetExcludedNodes(ctx context.Context, in *GetExcludedNodesRequest, opts ...grpc.CallOption) (*GetExcludedNodesResponse, error)
}

type pCEServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPCEServiceClient(cc grpc.ClientConnInterface) PCEServiceClient {
	return &pCEServiceClient{cc}
}

func (c *pCEServiceClient) CreateSRPolicy(ctx context.Context, in *CreateSRPolicyRequest, opts ...grpc.CallOption) (*CreateSRPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSRPolicyResponse)
	err := c.cc.Invoke(ctx, PCEService_CreateSRPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) DeleteSRPolicy(ctx context.Context, in *DeleteSRPolicyRequest, opts ...grpc.CallOption) (*DeleteSRPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSRPolicyResponse)
	err := c.cc.Invoke(ctx, PCEService_DeleteSRPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*GetSessionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionListResponse)
	err := c.cc.Invoke(ctx, PCEService_GetSessionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetSRPolicyList(ctx context.Context, in *GetSRPolicyListRequest, opts ...grpc.CallOption) (*GetSRPolicyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSRPolicyListResponse)
	err := c.cc.Invoke(ctx, PCEService_GetSRPolicyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetTED(ctx context.Context, in *GetTEDRequest, opts ...grpc.CallOption) (*GetTEDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTEDResponse)
	err := c.cc.Invoke(ctx, PCEService_GetTED_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, PCEService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) AddExcludedNode(ctx context.Context, in *AddExcludedNodeRequest, opts ...grpc.CallOption) (*AddExcludedNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddExcludedNodeResponse)
	err := c.cc.Invoke(ctx, PCEService_AddExcludedNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) RemoveExcludedNode(ctx context.Context, in *RemoveExcludedNodeRequest, opts ...grpc.CallOption) (*RemoveExcludedNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveExcludedNodeResponse)
	err := c.cc.Invoke(ctx, PCEService_RemoveExcludedNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEServiceClient) GetExcludedNodes(ctx context.Context, in *GetExcludedNodesRequest, opts ...grpc.CallOption) (*GetExcludedNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExcludedNodesResponse)
	err := c.cc.Invoke(ctx, PCEService_GetExcludedNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PCEServiceServer is the server API for PCEService service.
// All implementations must embed UnimplementedPCEServiceServer
// for forward compatibility.
type PCEServiceServer interface {
	CreateSRPolicy(context.Context, *CreateSRPolicyRequest) (*CreateSRPolicyResponse, error)
	DeleteSRPolicy(context.Context, *DeleteSRPolicyRequest) (*DeleteSRPolicyResponse, error)
	GetSessionList(context.Context, *GetSessionListRequest) (*GetSessionListResponse, error)
	GetSRPolicyList(context.Context, *GetSRPolicyListRequest) (*GetSRPolicyListResponse, error)
	GetTED(context.Context, *GetTEDRequest) (*GetTEDResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// AddExcludedNode/RemoveExcludedNode/GetExcludedNodes manage the global
	// node-exclusion set: router IDs kept out of CSPF consideration for every
	// dynamically-computed policy server-wide, independent of any single
	// policy's own SRPolicy.exclude. See the SRPolicy.exclude_router_ids /
	// exclude_sids comments for the equivalent per-policy mechanism.
	AddExcludedNode(context.Context, *AddExcludedNodeRequest) (*AddExcludedNodeResponse, error)
	RemoveExcludedNode(context.Context, *RemoveExcludedNodeRequest) (*RemoveExcludedNodeResponse, error)
	GetExcludedNodes(context.Context, *GetExcludedNodesRequest) (*GetExcludedNodesResponse, error)
	mustEmbedUnimplementedPCEServiceServer()
}

// UnimplementedPCEServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPCEServiceServer struct{}

func (UnimplementedPCEServiceServer) CreateSRPolicy(context.Context, *CreateSRPolicyRequest) (*CreateSRPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSRPolicy not implemented")
}
func (UnimplementedPCEServiceServer) DeleteSRPolicy(context.Context, *DeleteSRPolicyRequest) (*DeleteSRPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSRPolicy not implemented")
}
func (UnimplementedPCEServiceServer) GetSessionList(context.Context, *GetSessionListRequest) (*GetSessionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionList not implemented")
}
func (UnimplementedPCEServiceServer) GetSRPolicyList(context.Context, *GetSRPolicyListRequest) (*GetSRPolicyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSRPolicyList not implemented")
}
func (UnimplementedPCEServiceServer) GetTED(context.Context, *GetTEDRequest) (*GetTEDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTED not implemented")
}
func (UnimplementedPCEServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedPCEServiceServer) AddExcludedNode(context.Context, *AddExcludedNodeRequest) (*AddExcludedNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExcludedNode not implemented")
}
func (UnimplementedPCEServiceServer) RemoveExcludedNode(context.Context, *RemoveExcludedNodeRequest) (*RemoveExcludedNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveExcludedNode not implemented")
}
func (UnimplementedPCEServiceServer) GetExcludedNodes(context.Context, *GetExcludedNodesRequest) (*GetExcludedNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExcludedNodes not implemented")
}
func (UnimplementedPCEServiceServer) mustEmbedUnimplementedPCEServiceServer() {}
func (UnimplementedPCEServiceServer) testEmbeddedByValue()                    {}

// UnsafePCEServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PCEServiceServer will
// result in compilation errors.
type UnsafePCEServiceServer interface {
	mustEmbedUnimplementedPCEServiceServer()
}

func RegisterPCEServiceServer(s grpc.ServiceRegistrar, srv PCEServiceServer) {
	// If the following call panics, it indicates UnimplementedPCEServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PCEService_ServiceDesc, srv)
}

func _PCEService_CreateSRPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSRPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).CreateSRPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_CreateSRPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).CreateSRPolicy(ctx, req.(*CreateSRPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_DeleteSRPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSRPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).DeleteSRPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_DeleteSRPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).DeleteSRPolicy(ctx, req.(*DeleteSRPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_GetSessionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetSessionList(ctx, req.(*GetSessionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetSRPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSRPolicyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetSRPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_GetSRPolicyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetSRPolicyList(ctx, req.(*GetSRPolicyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetTED_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTEDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetTED(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_GetTED_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetTED(ctx, req.(*GetTEDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_AddExcludedNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExcludedNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).AddExcludedNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_AddExcludedNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).AddExcludedNode(ctx, req.(*AddExcludedNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_RemoveExcludedNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveExcludedNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).RemoveExcludedNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_RemoveExcludedNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).RemoveExcludedNode(ctx, req.(*RemoveExcludedNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCEService_GetExcludedNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExcludedNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServiceServer).GetExcludedNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PCEService_GetExcludedNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServiceServer).GetExcludedNodes(ctx, req.(*GetExcludedNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PCEService_ServiceDesc is the grpc.ServiceDesc for PCEService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PCEService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.pola.v1.PCEService",
	HandlerType: (*PCEServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSRPolicy",
			Handler:    _PCEService_CreateSRPolicy_Handler,
		},
		{
			MethodName: "DeleteSRPolicy",
			Handler:    _PCEService_DeleteSRPolicy_Handler,
		},
		{
			MethodName: "GetSessionList",
			Handler:    _PCEService_GetSessionList_Handler,
		},
		{
			MethodName: "GetSRPolicyList",
			Handler:    _PCEService_GetSRPolicyList_Handler,
		},
		{
			MethodName: "GetTED",
			Handler:    _PCEService_GetTED_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _PCEService_DeleteSession_Handler,
		},
		{
			MethodName: "AddExcludedNode",
			Handler:    _PCEService_AddExcludedNode_Handler,
		},
		{
			MethodName: "RemoveExcludedNode",
			Handler:    _PCEService_RemoveExcludedNode_Handler,
		},
		{
			MethodName: "GetExcludedNodes",
			Handler:    _PCEService_GetExcludedNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pola/v1/pola.proto",
}
